on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited
    branches:
      - main
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

name: Danger JS
jobs:
  dangerJS:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - run: |
          bun build dangerfile.ts --outfile dangerfile.js
          bunx danger@13.0.4 ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
