name: Unit tests

on:
  push:
    branches:
      - next
      - junction
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  build:
    name: Core Unit Tests, windows-latest
#    if: github.repository_owner == 'storybookjs'
    runs-on: windows-11-arm
    steps:
      - name: Offload GITHUB_WORKSPACE to D when available
        shell: pwsh
        run: |
          if (Test-Path 'D:\') {
            Write-Host "🎯 D: drive is available. Using D for caches."
           "TEMP=D:\temp" >> $env:GITHUB_ENV
           "TMP=D:\temp"  >> $env:GITHUB_ENV
           "npm_config_cache=D:\npm-cache" >> $env:GITHUB_ENV
           "YARN_GLOBAL_FOLDER=D:\yarn-global" >> $env:GITHUB_ENV
           "PLAYWRIGHT_BROWSERS_PATH=D:\playwright-browsers" >> $env:GITHUB_ENV           
          }
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install
        with:
          install-code-deps: true

      - name: compile
        run: yarn task --task compile --start-from=compile

      - name: Install Playwright Dependencies
        run: cd code && yarn exec playwright install chromium --with-deps

      - name: test
        run: yarn test
