name: Unit tests

on:
  push:
    branches:
      - next
      - devdrive
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  build:
    name: Core Unit Tests, windows-latest
    if: github.repository_owner == 'storybookjs'
    runs-on: windows-11-arm
    steps:
      - uses: samypr100/setup-dev-drive@v3
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install
        with:
          install-code-deps: true

      - name: compile
        run: yarn task --task compile --start-from=compile

      - name: Install Playwright Dependencies
        run: cd code && yarn exec playwright install chromium --with-deps

      - name: test
        run: yarn test
